server:
  tomcat:
    url-encoding: UTF-8
  servlet:
    context-path: /
spring:
  application:
    name: edu-spring-data-jdbc
  profiles:
    active: local
  banner:
    location: "classpath:banner.txt"
# cache 사용을 위해 cache name 설정
  cache:
    cache-names: employee
#  security:
#    user:
#      name: admin
#      password: admin
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080

# logging
logging:
  config: classpath:log4j2.xml

#jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  secret: CloudNativeKtEduSecretKey20240228CloudNativeKtEduSecretKey20240228CloudNativeKtEduSecretKey20240228
#  secret-key: 6e045a07fe01a595836901e3fea138730156ae02b792586df0e06ba62a91a8b1fdc091b49e4c0fe5e902f643b992294c93a53f1e059fb01623d90218977d1e5d

# app
app-info:
  app-name: "edu-spring-data-jdbc"
  title: "Cloud Native Edu API"
  build:
    version: '@project.version@'
    timestamp: '@app.build.timestamp@'
  user-id: "jake lee"
  org-id: "KT"
  desc: "EDU 관련 설명입니다."
  doc-url: "https://github.com/kt-cloudnative/education/"
  license: "Apache License"
  license_url: "https://github.com/kt-cloudnative/education/"
  version: "@app.build.timestamp@"
  doc-desc: "교육용"

