server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true

spring:
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: login-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/login/**
          filters:
            - RewritePath=/api/login/(?<path>.*),/$\{path}
        - id: command-service0
          uri: http://localhost:8081
          predicates:
            - Path=/**
            - Method=POST
          filters:
            - RewritePath=/(?<path>.*),/$\{path}
        - id: query-service
          uri: http://localhost:8082
          predicates:
            - Path=/**
            - Method=GET
          filters:
            - RewritePath=/(?<path>.*),/$\{path}
logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug
    com.kt: trace